directive @isAuthenticated on FIELD_DEFINITION
directive @isAdministrator on FIELD_DEFINITION

type User {
  uuid: ID!
  email: String!
  firstName: String
  lastName: String
  scope: String!
  refreshToken: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type Query {
  me: User! @isAuthenticated
  user(id: ID!): User! @isAuthenticated @isAdministrator
  users: [User!] @isAuthenticated @isAdministrator
}

type Mutation {
  signup(email: String!, password: String!): AuthPayload
  login(email: String!, password: String!): AuthPayload
  updateUser(
    firstName: String
    lastName: String
  ): User @isAuthenticated
  deleteUser: User @isAuthenticated
}
